### ISSUE TITLE
Whitelist files/URLs on mod_evasive

### ISSUE THREAD

**Issue by nunoperalta** [jvdmr/mod_evasive#10]
Hello,

As soon as I enabled this module (the original one), I noticed that a number of IPs were blocked straight away, and all of those users use Safari on iOS.

After a quick investigation, I saw that those users were requesting "serviceworker.js" several times. This is a bug and this file should only be fetched once.

I reported that bug to Apple, but unfortunately the mess is already done and many users will continue to fetch this file several times -- https://bugs.webkit.org/show_bug.cgi?id=187435

mod_evasive allows me to whitelist IPs, but would it be possible to implement a way I can also whitelist files or folders so that those will not count towards DOSPageCount or DOSSiteCount?

I'm only getting alerts and blocks for those who are fetching "serviceworker.js" so much.

Thank you very much.

**Comment by jvdmr** [comment]
Closed with release 2.2.0, which adds DOSWhitelistUri configuration using regex.

Hope that helps!

**Comment by nunoperalta** [comment]
Thank you very much for this!! :)

Much better and supporting answer than I had got in https://github.com/shivaas/mod_evasive/issues/13 , a few years ago!
