### ISSUE TITLE
Enabling mod_evasive results in 500 error

### ISSUE THREAD

**Issue by MagnusEnger** [jvdmr/mod_evasive#2]
Thanks for taking the effort to update mod_evasive to work with Apache 2.4. Much appreciated! 

I'm on Debian 8.9, with "Apache/2.4.10 (Debian) mpm-itk/2.4.7-02 OpenSSL/1.0.1t".

I have not been able to make the module work... I clone the repo, and dpkg-install the included .deb file. I have added a .conf file that looks like this:

```
<IfModule mod_evasive24.c>
    DOSHashTableSize    3097
    DOSPageCount        2
    DOSSiteCount        50
    DOSPageInterval     1
    DOSSiteInterval     1
    DOSBlockingPeriod   10

    DOSEmailNotify      me@example.com
    #DOSSystemCommand    "su - someuser -c '/sbin/... %s ...'"
    DOSLogDir           "/var/log/apache2/evasive"
</IfModule>
```
I have tested with different values in the IfModule, including "mod_evasive.c" (as given in the README) and "evasive_module", but to no avail. 

The contents of evasive.load looks like this:

```
LoadModule evasive_module     /usr/lib/apache2/modules/mod_evasive.so
```

Whatever I do, when the module is enabled, my websites respond with a 500 error, and there is no more detail in /var/log/apache2/error.log. When I disable the module everything works as normal again. 

Any pointers would be most welcome! :-)

**Comment by jvdmr** [comment]
Hi, sorry for the long wait, I've only now had time to look into this issue.

Some thoughts:
* It should definitely be `<IfModule mod_evasive.c>`. The reason for this is when building the .so (and the .deb file), I rename the mod_evasive24.c to mod_evasive.c, as described in the README.
  * I've just tested this, by adding some nonsense in the configuration between the <IfModule> tags: Apache starts fine with `<IfModule mod_evasive24.c>foobar...` but throws an error during startup (and refuses to start) with `<IfModule mod_evasive.c>foobar...` saying 'Invalid command 'foobar', perhaps misspelled or defined by a module not included in the server configuration'.
* There's no `DOSEnabled true` line in your config. Without that line, mod_evasive won't be activated. So even though the config is present, it shouldn't affect any websites in any way. That's where the problem starts, of course...
* Unfortunately, I can't currently reproduce the issue (even with `DOSEnabled true`added to the config). I'm on different Debian (9.2) and Apache (2.4.25) versions though, so I'm going to try and setup an environment matching your setup to hopefully find the issue.

**Comment by jvdmr** [comment]
I can't reproduce the issue on the matching versions of Debian and Apache either. I've found a different, possibly related, issue: when mpm_itk is enabled, mod_evasive simply doesn't work at all (for me).

* Is disabling mpm_itk an option for you? At least for testing if that makes your issue go away, and possibly as a fix altogether?
* Is there anything in any other logfile in /var/log/apache2 or any subdirectory thereof?
* Could you add `LogLevel debug` to your /etc/apache2/apache2.conf and check the logfiles again for any more information?
* Could you possibly send me the entire Apache config directory (or a minimal test setup that shows the issue, or at least anything related to mpm_itk)?

I've created #3 for the mpm_itk issue, but as always can't promise to have a fix for it soon...
