### ISSUE TITLE
DOSWhitelistUri not implemented in mod_evasive24win.c 

### ISSUE THREAD

**Issue by dogzipp** [jvdmr/mod_evasive#20]
If possible please add it

**Comment by responsemlanger** [comment]
Hi,
we need urgent this function in Windows Apache. Could you please add this? 

Thanks a lot.

Regards,
Marco

**Comment by jvdmr** [comment]
This _should_ now be available in Windows too (see release 2.3.0). However, as mentioned before, I have no way of testing or even compiling this, so for all I know `mod_evasive24win.c` won't even compile now. If this is the case, please let me know ASAP so I can revert the change until someone can help me test this on Windows.

If it does work, please let me know as well! 🙏
