### ISSUE TITLE
Not working doswhitelisturi with query params in linux

### ISSUE THREAD

**Issue by abhishekjadhav4** [jvdmr/mod_evasive#22]
I am looking to whitelist following URL 
http://localhost/jasperserver/flow.html?_flowId=searchFlow

Please share the value of DOSwhitelistURI

**Comment by jvdmr** [comment]
That would be `DOSWhitelistUri /jasperserver/flow.html`

**Comment by abhishekjadhav4** [comment]
Is there any way to blacklist a specific URL by mentioning in whitelistURI? 
Any regex or something else we can use?
I want to blacklist only "/j_spring_security_check" and apart from this all URI should be accepted.
