### ISSUE TITLE
New version change log

### ISSUE THREAD

**Issue by SteffenAL** [jvdmr/mod_evasive#7]
There is some updated and i miss now the discussions with you in issues (2017). In that discussions I saw clearly what was changed.

The release version is now 1.0. And former I had 1.10.x.

Can you update the change log, so we are in sync.

Cheers,

Steffen

**Comment by jvdmr** [comment]
You're absolutely right, and it's a small effort keeping the changelog updated. Done!

Please let me know if anything's not clear or missing.
